### PR TITLE
Changes for debug input/output (hacked)

### PR DESCRIPTION
**Pull request by rogalmic**

### CODE REVIEW

**Comment by krader1961** [comment]
@rocky Are you still maintaining this project? The open source ksh project, https://github.com/att/ast/, is running your tests periodically. So seeing a PR more than a year old is worrisome. Should this PR be rejected or merged?

**Review by rocky — APPROVED** [review]

**Comment by rocky** [comment]
Hmmm... sorry this one slipped through the cracks. 

As for maintaing kshdb, I'm still interested in it. But I generally go by the ranking and this one is a it behind zshdb. In fact, haven't upvoted it. 

However I'll put it on the list of things to sync up to the level of zshdb and put out another release, hopefully before the end of the ear.

**Comment by krader1961** [comment]
Wow. That was a very quick response. It looks like you still care about this test suite being relevant to the ksh shell as it evolves. Something I appreciate.

I'm curious if you have been tracking the changes to the ksh master branch at https://github.com/att/ast/.

**Comment by rocky** [comment]
> I'm curious if you have been tracking the changes to the ksh master branch at https://github.com/att/ast/

Sorry, no. Is there something I should know?

**Comment by krader1961** [comment]
@rocky No, other than that ksh is being updated after the project was open-sourced after ksh93v- (which is slightly nebulous). Which means that it is theoretically possible your tests might need to be updated as a consequence of fixing bugs.

**Comment by rocky** [comment]
kshdb requres version [2014-12-24 or greater](https://github.com/rocky/kshdb/blob/master/configure.ac#L38) and it even says that in the project heading. 

I note that Ubuntu Ermine which just comes out ships with 93u+20120801 which is too early. 

Perhaps you should consier coming out with an official release rather than a rolling one, say 93v+2019... or something like that so that Ubuntu and other distributions know that is stable. 

Then people are more likely to use both what is in the github repository as well as kshb. As is, Ubuntu can't bundle kshdb because there is no corresponding ksh. 

In fact, most repositories don't have it. See https://repology.org/project/ksh/versions

**Comment by krader1961** [comment]
@rocky FWIW, we have made an official release, version 2020.0.0, that is based on ksh93v- and is slowly being adopted by distros and mechanisms like Homebrew. The repology.org link reflects that state of affairs. There will almost certainly be a 2020.1.0 minor release early next year.

**Pull request merged**
